apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mexeniz/argoflow
    targetRevision: v0.1.0
    path: monitoring-resources
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
